ARG SOPS_VERSION=3.11.0

# apparently, /usr/local/bin doesn't persist, so we use /usr/bin
RUN --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    curl -Lo /usr/bin/sops "https://github.com/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64" \
    && chmod +x /usr/bin/sops
